source_data1 <- mutate(source_data,week_day = paste(Date,Time,sep = " "))
source_data1 <- mutate(source_data1,Sub_metering_1 =as.numeric(Sub_metering_1))
source_data1 <- mutate(source_data1,Sub_metering_2 =as.numeric(Sub_metering_2))
source_data1 <- mutate(source_data1,Sub_metering_3 =as.numeric(Sub_metering_3))
time1 <- strptime(source_data1$week_day,"%d/%m/%Y %H:%M:%S")
plot(time1,source_data1$Sub_metering_1,type = "l",xlab="",ylab = "Energy sub metering",col="black")
lines(time1,source_data1$Sub_metering_2,col="red")
lines(time1,source_data1$Sub_metering_3,col="blue")
legend("topright", lty = 1, col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()